version: "3.8"

services:
  frontend:
    build:
      context: ./reactvite-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - ecommerce-network

  backend:
    build:
      context: ./java/apiecomerce
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
