services:
  - type: web
    name: frontend
    env: docker
    plan: free
    buildCommand: "npm install node styled-components && npm run build"
    dockerfilePath: ./reactvite-app
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: backend
    env: docker
    plan: free
    buildCommand: "./mvnw clean package"
    dockerfilePath: ./java/apiecomerce
