# Exported from Render on 2024-11-11T12:28:18Z
services:
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/danpqdan/ECommerceFullStack
    branch: reactVite
    plan: free
    envVars:
      - key: NODE_ENV
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./reactvite-app
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/danpqdan/ECommerceFullStack
    branch: reactVite
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./java/apiecomerce
version: "1"
