# Etapa de build
FROM node:18-alpine AS build

WORKDIR /reactvite-app
COPY package*.json ./
RUN npm install
RUN npm install styled-components react-router-dom swiper
COPY . .
RUN npm run build

# Etapa de produção
FROM nginx:alpine

# Copia os arquivos da build para o diretório do nginx
COPY --from=build /reactvite-app/build /usr/share/nginx/html

# Expondo a porta do nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
